//APP ACTION TYPES

export const INIT_API_CALL = 'INIT_API_CALL';
export const TERMINATE_API_CALL = 'TERMINATE_API_CALL';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_RANGE = 'UPDATE_RANGE';
export const SET_APP_NET_STATE_BT = 'SET_APP_NET_STATE_BT';
export const SET_INTERNET_PROMPT = 'SET_INTERNET_PROMPT';
export const SET_BT_PROMPT = 'SET_BT_PROMPT';
export const DELETE_PROMPT = 'DELETE_PROMPT';
export const INIT_LOADING = 'INIT_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const HALT_APP_INTERFACE = 'HALT_APP_INTERFACE';
export const SET_APP_READY = 'SET_APP_READY';
export const SET_PROMPT = 'SET_PROMPT';
export const VERSION_CHECK_SUCCESS = 'VERSION_CHECK_SUCCESS';
export const VERSION_CHECK_FAIL = 'VERSION_CHECK_FAIL';
export const SET_GENERAL_SETTINGS = 'SET_GENERAL_SETTINGS';

//PROFILE ACTION TYPES

export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_ACTIVE_PROFIE_TYPE = 'SET_ACTIVE_PROFIE_TYPE';
export const CONTACTS_FETCH_SUCCESS = 'CONTACTS_FETCH_SUCCESS';

//DISCOVER ACTION TYPES

export const DISCOVER_PEOPLE_SUCCESS = 'DISCOVER_PEOPLE_SUCCESS';
export const DISCOVER_SPONSORS_SUCCESS = 'DISCOVER_SPONSORS_SUCCESS';
export const BT_MANAGER_RUNNING_STATE = 'BT_MANAGER_RUNNING_STATE';
export const IS_DISCOVERING_START = 'IS_DISCOVERING_START';
export const IS_DISCOVERING_DONE = 'IS_DISCOVERING_DONE';

//CHAT ACTION TYPES

export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING';
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS';
export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR';
export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE';
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS';
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR';
export const SET_THREADS = 'SET_THREADS';
export const SET_UNREAD_THREADS = 'SET_UNREAD_THREADS';
export const BT_CHAT_MESSAGE_SUCCESS = 'BT_CHAT_MESSAGE_SUCCESS';

// HOTEL ACTION TYPES

export const HOTEL_LOADING = 'HOTEL_LOADING';
export const HOTEL_LIST = 'HOTEL_LIST';
export const HOTEL_LIST_ERROR = 'HOTEL_LIST_ERROR';
export const VIEW_HOTEL = 'VIEW_HOTEL';
export const TOUR_LIST = 'TOUR_LIST';
export const TOUR_ERROR = 'TOUR_ERROR';
export const CITY_LIST = 'CITY_LIST';
export const STOP_LIST = 'STOP_LIST';
export const LIST_ERROR = 'LIST_ERROR';
export const BOOK_TOUR = 'BOOK_TOUR';
export const BOOK_ERROR = 'BOOK_ERROR';
export const BOOKING_TYPE = 'BOOKING_TYPE';
export const AIRPORT_LIST = 'AIRPORT_LIST';
export const VEHICLE_PRICE = 'VEHICLE_PRICE';
export const BOOK_AIRPORT_TRANSFER = 'BOOK_AIRPORT_TRANSFER';
export const LIST_BOOKED_TOURS = 'LIST_BOOKED_TOURS';
export const VIEW_BOOKED_TOUR = 'VIEW_BOOKED_TOUR';
export const LIST_BOOKED_TRANSFERS = 'LIST_BOOKED_TRANSFERS';
export const VIEW_BOOKED_TRANSFER = 'VIEW_BOOKED_TRANSFER';
export const PAYMENT_INTENT = 'PAYMENT_INTENT';
export const PAYMENT_CONFIRM = 'PAYMENT_CONFIRM';
export const GET_PAYMENT = 'GET_PAYMENT';
export const TRANSFER_PAYMENT_INTENT = 'TRANSFER_PAYMENT_INTENT';
export const TRANSFER_PAYMENT_CONFIRM = 'TRANSFER_PAYMENT_CONFIRM';
export const GET_TRANSFER_PAYMENT = 'GET_TRANSFER_PAYMENT';
export const BOOK_TICKET = 'BOOK_TICKET';
export const TICKET_TOUR_LIST = 'TICKET_TOUR_LIST';
export const BOOK_GUIDE_TICKET = 'BOOK_GUIDE_TICKET';
export const TICKET_GUIDE_TOUR_LIST = 'TICKET_GUIDE_TOUR_LIST';
